# Deep Learning at AdvendtureWorks: Predictive Modelling through classic machine learning models

In [1]:
import numpy as np
from os.path import join
from os import listdir

## Construction du data set

In [2]:
# Construction du dataset
data = np.empty([2122, 128, 128, 3])
label = np.empty([2122])
i = 0
label_mapping = {}
root = '../Data/gear_images_npy'

In [3]:
for fol_nber, folder in enumerate(listdir(root)):
    label_mapping[fol_nber] = folder
    for imgfile in listdir(join(root,folder)):
        npimg = np.load(join(root, folder, imgfile))
        data[i,:,:,:] = npimg
        label[i] = fol_nber
        i+=1
        
np.savez('../Data/dataset.npz', x=data, y=label)

In [ ]:
print(data.shape)

In [10]:
data = np.load('../Data/dataset.npz')

In [15]:
data.files
X = data['x']
y = data['y']

In [17]:
print(type(X))
print(X.shape)
print(y.shape)

<class 'numpy.ndarray'>
(2122, 128, 128, 3)
(2122,)


## Split échantillon d'apprentissage et de test

In [19]:
from sklearn.model_selection import train_test_split

X_training, X_testing, y_training, y_testing = train_test_split(X.reshape(2122, -1), y, test_size=0.3, random_state=42)

In [21]:
print(X_training.shape)
print(X_testing.shape)
print(y_training.shape)
print(y_testing.shape)

(1485, 49152)
(637, 49152)
(1485,)
(637,)


## Machine Learning

### Arbre de décision

In [52]:
from sklearn.tree import DecisionTreeClassifier 

tree_model = DecisionTreeClassifier(max_depth = 5)

tree_model.fit(X_training, y_training)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=5,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [53]:
tree_predictions = tree_model.predict(X_testing) 

In [54]:
# construction de la matrice de confusion
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_testing, tree_predictions) 
print(cm)

[[  0   0   1  18   2   0   1   0   0   0   1   1]
 [  0  17   0   0   2   3   0   0   4   0   2   0]
 [  0   0  70  19   2   3   5   0   0   1   0   0]
 [  0   0   0  20   4   0   1   0   1   0   2   8]
 [  0   3   0   1  40   4   0  10   8   0   0   2]
 [  0   0   0   0   0 105   0   1  12   3   2   0]
 [  0   1   0   9   4   1  16   0  15   0   1   1]
 [  0   0   3   3   1   0   0  14   1   0   1   0]
 [  0   0   0   0   0  53   0   2  22   0   0   1]
 [  0   3   1   0   1   2   0   1   5   0   0   1]
 [  0   1   1   1   4   2   0   2   5   0  39   3]
 [  0   0   0   0   0   1   0   0   0   0   5  31]]


In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_testing, tree_predictions)

0.5871271585557299

### K plus proches voisins

In [56]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=10)

knn_model.fit(X_training, y_training)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')

In [57]:
knn_predictions = knn_model.predict(X_testing)

In [58]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_testing, knn_predictions) 
print(cm)

[[ 24   0   0   0   0   0   0   0   0   0   0   0]
 [  0  28   0   0   0   0   0   0   0   0   0   0]
 [  9   0  88   0   0   2   0   0   0   0   0   1]
 [  9   0   0  17   0   2   0   0   0   0   0   8]
 [  0   0   0   0  50  12   0   1   0   0   4   1]
 [  1   0   1   0   0 119   0   0   2   0   0   0]
 [  0   0   1   0   2   3  36   0   3   0   0   3]
 [  0   0   3   0   0   2   0  14   1   0   0   3]
 [  0   0   0   0   0  50   0   0  28   0   0   0]
 [  0   0   1   0   0   9   0   0   2   0   1   1]
 [  1   0   0   0   0   7   0   0   3   0  44   3]
 [  0   0   0   0   0   0   0   0   0   0   0  37]]


In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(y_testing, knn_predictions)

0.7613814756671899

## Sauvegarde des modèles

In [60]:
import pickle

pickle.dump(model_tree, open('../Output/decision_tree.pkl', 'wb'))

In [62]:
from sklearn.externals import joblib

joblib.dump(knn_model, '../Output/knn.pkl')

['../Output/knn.pkl']